# .github/workflows/ci.yaml

name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Run the script
        run: scripts/allbuild.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: ./output

  prod:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true

      - name: Install Vercel CLI
        run: bun install --global vercel@latest

      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: output
          path: ./output

      - uses: amondnet/vercel-action@v25 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-args: "--prod" #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
          working-directory: ./output
