name: Page Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Copy Index.html
        run: |
          mkdir -p output
          cp -r src/* output/

      - name: Run Scripts
        run: |
          chmod +x scripts/allbuild.sh
          ./scripts/allbuild.sh

      - name: Test
        run: |
          ls -la output
          bun install

      - uses: actions/upload-artifact@v4
        with:
          name: my_site
          path: output
      - uses: actions/upload-pages-artifact@v3
        with:
          path: output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
